config/routes.rb
CoConceptualize::Application.routes.draw do

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :projects
  resources :users

  get "home/index"
  match "/node/:id" => "node#test"
  match "/node/json/:id" => "node#index"
  match "/node/update" => "ideas#update"

  match "/projects/:id" => "node#test"

  root :to => "home#index"

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  attr_accessible :detail, :project_id, :title, :user_id ,:ancestor
  belongs_to :project
  belongs_to :user
  belongs_to :idea
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @ideas }
    end
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea = Idea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @idea }
    end
  end

  # GET /ideas/new
  # GET /ideas/new.json
  def new
    @idea = Idea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @idea }
    end
  end

  # GET /ideas/1/edit
  def edit
    @idea = Idea.find(params[:id])
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(params[:idea])

    respond_to do |format|
      if @idea.save
        format.html { render :json => @idea.id }
        #format.html { redirect_to @idea, :notice => 'Idea was successfully created.' }
        format.json { render :json => @idea, :status => :created, :location => @idea }
      else
        format.html { render :action => "new" }
        format.json { render :json => @idea.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ideas/1
  # PUT /ideas/1.json
  def update
    @idea = Idea.find(params[:id])

    respond_to do |format|
      if @idea.update_attributes(params[:idea])
        format.html { redirect_to @idea, :notice => 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @idea.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end
  
  def showidea
    @id = params[:id]
    @ideas = Idea.find_by_project_id(:id).each do |idea|
      format.json{ render :json => @idea}
    end
    
    
  end
end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.number_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :detail %><br />
    <%= f.text_field :detail %>
  </div>
  <div class="field">
    <%= f.label :ancestor %><br />
    <%= f.text_field :ancestor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<h1>Listing ideas</h1>

<table>
  <tr>
    <th>User</th>
    <th>Project</th>
    <th>Title</th>
    <th>Detail</th>
    <th>Ancestor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ideas.each do |idea| %>
  <tr>
    <td><%= idea.user_id %></td>
    <td><%= idea.project_id %></td>
    <td><%= idea.title %></td>
    <td><%= idea.detail %></td>
    <td><%= idea.ancestor %></td>
    <td><%= link_to 'Show', idea %></td>
    <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
    <td><%= link_to 'Destroy', idea, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Idea', new_idea_path %>
<%= #link_to 'Show', showidea_idea_path
%>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @idea.user_id %>
</p>

<p>
  <b>Project:</b>
  <%= @idea.project_id %>
</p>

<p>
  <b>Title:</b>
  <%= @idea.title %>
</p>

<p>
  <b>Detail:</b>
  <%= @idea.detail %>
</p>

<p>
  <b>Ancestor:</b>
  <%= @idea.ancestor %>
</p>


<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/showidea.html.erb
<h1>Ideas#showidea</h1>
<p>Find me in app/views/ideas/showidea.html.erb</p>


<table>
  <tr>
    <th>User</th>
    <th>Project</th>
    <th>Title</th>
    <th>Detail</th>
    <th>Ancestor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ideas.each do |idea| %>
  <tr>
    <td><%= idea.user_id %></td>
    <td><%= idea.project_id %></td>
    <td><%= idea.title %></td>
    <td><%= idea.detail %></td>
    <td><%= idea.ancestor %></td>
    <td><%= link_to 'Show', idea %></td>
    <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
    <td><%= link_to 'Destroy', idea, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>