config/routes.rb
CoConceptualize::Application.routes.draw do

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :projects
  resources :users

  get "home/index"
  match "/node/:id" => "node#test"
  match "/node/json/:id" => "node#index"
  match "/node/update" => "ideas#update"

  match "/projects/:id" => "node#test"

  root :to => "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :project_users
	has_many :projects, :through => :project_users
	attr_accessible :email, :firstname, :id, :lastname, :password, :username, :password, :password_confirmation
	has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  skip_before_filter :authorize
  
  # GET /users
  # GET /users.json
  def index
    redirect_to :controller => 'users', :action => 'new'
  end

  def signed_in?
    !session[:user_id].nil?
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    if signed_in?
      redirect_to projects_url
    else
      @user = User.new
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @user }
      end
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Your account has been successfully created!' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <div class="field">
    <%= f.text_field :username, :placeholder => 'Username' %>
  </div>
  <div class="field">
    <%= f.password_field :password, :type => 'password', :placeholder => 'Password' %>
  </div>
  <div class="field">
    <%= f.password_field :password_confirmation, :type => 'password', :placeholder => 'Password Confirm' %>
  </div>
  <div class="field">
    <%= f.text_field :firstname, :placeholder => 'First Name' %>
  </div>
  <div class="field">
    <%= f.text_field :lastname, :placeholder => 'Last Name' %>
  </div>
  <div class="field">
    <%= f.text_field :email, :placeholder => 'Email Address' %>
  </div>
  <div class="actions">
    <div><button id="signup-button">Join Now!</button></div>
  </div>
<% end %>

app/views/users/edit.html.erb
<section id="signup">
	<div id="nav">
		<div id="logo">
			<a href="/home/index">CoConceptualize</a>
		</div>
		<ul>
			<li><a href="/home/index">Home</a></li>
			<li class="sepa">·</li>
			<li><a href="/home/index#about" onClick="smoothScroll('about','fast')">About</a></li>
			<li class="sepa">·</li>
			<li><a href="/home/index#contact" onClick="smoothScroll('contact','fast')">Contact</a></li>
		</ul>
	</div>
	<div id="signup-box">
		<div class="title">Sign Up Now</div>
		<div id="register_error"></div>
	<%= render 'form' %>
	</div>
</section>
<div id="copyright-bar">
	<span id="copyright-text"></span>
	<img src="/images/copyright.png" />
</div>

app/views/users/new.html.erb
<section id="signup">
	<div id="nav">
		<div id="logo">
			<a href="/home/index">CoConceptualize</a>
		</div>
		<ul>
			<li><a href="/home/index">Home</a></li>
			<li class="sepa">·</li>
			<li><a href="/home/index#about" onClick="smoothScroll('about','fast')">About</a></li>
			<li class="sepa">·</li>
			<li><a href="/home/index#contact" onClick="smoothScroll('contact','fast')">Contact</a></li>
		</ul>
	</div>
	<div id="signup-box">
		<div class="title">Sign Up Now</div>
		<div id="register_error"></div>
		<%= render 'form' %>
	</div>
</section>
<div id="copyright-bar">
	<span id="copyright-text"></span>
	<img src="/images/copyright.png" />
</div>

app/views/users/show.html.erb
<section id="signup">
  <div id="nav">
    <div id="logo">
      <a href="/home/index">CoConceptualize</a>
    </div>
    <ul>
      <li><a href="/home/index">Home</a></li>
      <li class="sepa">·</li>
      <li><a href="/home/index#about" onClick="smoothScroll('about','fast')">About</a></li>
      <li class="sepa">·</li>
      <li><a href="/home/index#contact" onClick="smoothScroll('contact','fast')">Contact</a></li>
    </ul>
  </div>
  <div id="signup-success">
    <p id="notice"><%= notice %></p>
    <p>Username<b><%= @user.username %></b></p>
    <p>First Name<b><%= @user.firstname %></b></p>
    <p>Last Name<b><%= @user.lastname %></b></p>
    <p>Email Address<b><%= @user.email %></b></p>
  </div>
<%= link_to 'Edit', edit_user_path(@user) %>
</section>
<div id="copyright-bar">
  <span id="copyright-text"></span>
  <img src="/images/copyright.png" />
</div>