config/routes.rb
CoConceptualize::Application.routes.draw do

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :projects
  resources :users

  get "home/index"
  match "/node/:id" => "node#test"
  match "/node/json/:id" => "node#index"
  match "/node/update" => "ideas#update"

  match "/projects/:id" => "node#test"

  root :to => "home#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :project_users
	has_many :users, :through => :project_users
	attr_accessible :date_created, :id, :name, :assignuser

	def assignuser
	end

	def assignuser=(arg)
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  # GET /projects
  # GET /projects.json
  def index
    @user = User.find_by_id(session[:user_id])
    @projects = @user.projects
    
    #@user.projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @project_ideas = Idea.where("project_id = ?", params[:id])
    @user = User.find(session[:user_id])

    @project_ideas.each do |p_idea|
      if p_idea.ancestor == nil
        @n_id = p_idea.id
        @idea = p_idea
      end
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  #{ render :xml => @users }
      #format.json  { render :file => "index.json.erb", :content_type => 'application/json' }
      format.json #{render :json => @project_ideas}
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    current_user = User.find_by_id(session[:user_id])
    assign_user = User.find_all_by_username(params[:project][:assignuser])

    respond_to do |format|
      if @project.save
        @project.users << current_user
        @project.users << assign_user
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])
    assign_user = User.find_all_by_username(params[:project][:assignuser])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        @project.users << assign_user
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.text_field :name, :placeholder => 'Name of Project' %>
  </div>
  <div class="field">
    <%= f.text_field :assignuser, :placeholder => 'Type in a username to assign' %>
  </div>
  <div class="actions">
    <div><button id="signup-button">Submit</button></div>
  </div>
<% end %>

app/views/projects/edit.html.erb
<section id="login">
  <div id="nav">
    <div id="logo">
      <a href="/home/index">CoConceptualize</a>
    </div>
    <ul>
      <li><a href="/home/index">Home</a></li>
      <li class="sepa">·</li>
      <li><a href="/home/index#about" onClick="smoothScroll('about','fast')">About</a></li>
      <li class="sepa">·</li>
      <li><a href="/home/index#contact" onClick="smoothScroll('contact','fast')">Contact</a></li>
    </ul>
  </div>
	<div id="new-or-edit-project">
		<h1>Edit project</h1>
		<%= render 'form' %>
		<%= link_to 'Back', projects_path %>
	</div>
</section>
<div id="copyright-bar">
  <span id="copyright-text"></span>
  <img src="/images/copyright.png" />
</div>

app/views/projects/index.html.erb
<section id="login">
  <div id="nav">
    <div id="logo">
      <a href="/home/index">CoConceptualize</a>
    </div>
    <ul>
      <li><a href="/home/index">Home</a></li>
      <li class="sepa">·</li>
      <li><a href="/home/index#about" onClick="smoothScroll('about','fast')">About</a></li>
      <li class="sepa">·</li>
      <li><a href="/home/index#contact" onClick="smoothScroll('contact','fast')">Contact</a></li>
    </ul>
  </div>
  <div id="toolbar">
    <div id="new-project">
       <%= link_to 'New Project', new_project_path %>
    </div>
    <div id="logout">
      <%= link_to 'Log Out', logout_path,
          :method => :delete,
          :confirm => 'Are you sure you want to logout?',
          :controller => "sessions" 
      %>
    </div>
  </div>
  <div id="projects-listing">
    <h1>Hello <span style="color:#17a5d4"><b><%= @user.username %></b></span>, welcome to your projects list!</h1>
    <table id="projects-list" cellpadding="0" cellspacing="0">
       <% if @projects.blank? %>
        <div class="no-project-found">
          You currently have no project!
        </div>
        <% else %>
          <tr>
            <th width="40%">Project Name</th>
            <th width="30%">Created On</th>
            <th width="30%" colspan="3">Action</th>
          </tr>
          <% @projects.each do |project| %>
          <tr>
            <td><%= link_to project.name, "/node/" + project.id.to_s %></td>
            <td><%= project.created_at %></td>
            <td colspan="3">
              <%= link_to 'Edit', edit_project_path(project) %>
              &nbsp;|&nbsp;
              <%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
          <% end %>
        <% end %>
    </table>
  </div>
</section>
<div id="copyright-bar">
  <span id="copyright-text"></span>
  <img src="/images/copyright.png" />
</div>

app/views/projects/new.html.erb
<section id="login">
  <div id="nav">
    <div id="logo">
      <a href="/home/index">CoConceptualize</a>
    </div>
    <ul>
      <li><a href="/home/index">Home</a></li>
      <li class="sepa">·</li>
      <li><a href="/home/index#about" onClick="smoothScroll('about','fast')">About</a></li>
      <li class="sepa">·</li>
      <li><a href="/home/index#contact" onClick="smoothScroll('contact','fast')">Contact</a></li>
    </ul>
  </div>
	<div id="new-or-edit-project">
		<h1>Creating a new project</h1>
		<%= render 'form' %>
		<%= link_to 'Back', projects_path %>
	</div>
</section>
<div id="copyright-bar">
  <span id="copyright-text"></span>
  <img src="/images/copyright.png" />
</div>

app/views/projects/show.html.erb
<script src="/assets/demo.js?body=1" type="text/javascript"></script>
<script src="/assets/websocket.js?body=1" type="text/javascript"></script>
<section id="login">
	<div id="nav">
		<div id="logo">
		  <a href="/home/index">CoConceptualize</a>
		</div>
		<ul>
		  <li><a href="/home/index">Home</a></li>
				<li class="sepa">·</li>
				<li><a href="/home/index#about" onClick="smoothScroll('about','fast')">About</a></li>
				<li class="sepa">·</li>
				<li><a href="/home/index#contact" onClick="smoothScroll('contact','fast')">Contact</a></li>
		</ul>
	</div>
	<div id="main-canvas" class="cf">
		<div id="online-user">
			<h3>Online Users</h3>
			<ul id="online_users"></ul>
		</div>
		<div id="concept-manager">
			<h3>The Concepts</h3>
			<form id="update">
				<div>
					Current Sub-Concept
					<input type="text" id="node_title" name="title"  />
				</div>
				<div>
					Detail
					<input type="text" id="node_detail" name="detail"  />
				</div>
				<input type="hidden" id="node_id" name="id" value = "<%= @n_id %>" />
			</form>
			<button id="button_update">update</button>
			<h3>New Sub-Concept</h3>
			<form id="create">
				<input type="hidden" id="new_node_pid" name="project_id" value="<%= params[:id]%>" />
				<input type="hidden" id="new_node_uid" name="user_id" value="<%= @user[:id] %>" />
				<input type="hidden" id="new_node_uname" name="user_name" value="<%= @user[:username] %>" />
				<input type="hidden" id="ancestor" name="ancestor"/>
				Title
				<input type="text" id="new_node_title" name="title"  />
				Detail
				<input type="text" id="new_node_detail" name="detail"  />
			</form>
			<button id="button_create">add</button>	
		</div>
		<div id="canvas">
			<div class="heading">
				<div class="back"><%= link_to 'Back', projects_path %></div>
				<%= @project.name %>
			</div>
			<div class="graph">
				<canvas id="viewport" width="600" height="600"></canvas>
			</div>
		</div>
	</div>
</section>
<div id="copyright-bar">
	<span id="copyright-text"></span>
	<img src="/images/copyright.png" />
</div>